allowBuilds:
  '@biomejs/biome': true
  esbuild: true
overrides:
  "react-reconciler": "0.33.0"
  "react-iiif-vault": "2.0.17"
  "@iiif/parser": "2.2.13"
  "@iiif/helpers": "1.6.0"
  "@atlas-viewer/atlas": "3.2.3"
  "react": "^19.2.0"
  "react-dom": "^19.2.0"
